# Generated by Django 4.2.16 on 2024-09-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ping', 'Ping'), ('content', 'Content')], default='ping', max_length=100)),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('Telegram', 'Telegram')], default='email', max_length=100)),
                ('settings', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_sent_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.recipient')),
                ('related_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.check')),
            ],
            options={
                'unique_together': {('related_check', 'recipient', 'notification_sent_at')},
            },
        ),
        migrations.AddField(
            model_name='check',
            name='recipients',
            field=models.ManyToManyField(through='snippets.NotificationEvent', to='snippets.recipient'),
        ),
        migrations.AddField(
            model_name='check',
            name='tags',
            field=models.ManyToManyField(to='snippets.tag'),
        ),
        migrations.AddField(
            model_name='check',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.notificationtemplate'),
        ),
    ]
