# Generated by Django 4.2.16 on 2024-09-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_check_notificationtemplate_recipient_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='frequency',
            field=models.CharField(default='0 * * * *', max_length=100),
            preserve_default=False,
        ),
    ]
